### ISSUE TITLE
Bug in Post to Discord Channel

### ISSUE THREAD

**Issue by Marlon154** [Fachschaft-FB12/Digitales-Brett-Viewer#3]
Build failed
Triggered workflow by hand ->  also failed

```
Run python python/rssfeed.py
Traceback (most recent call last):
  File "python/rssfeed.py", line 29, in <module>
    response = requests.post(os.environ.get("DISCORD_URL"), json={ "content" : message })
  File "/opt/hostedtoolcache/Python/3.8.***2/x64/lib/python3.8/site-packages/requests/api.py", line ***7, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.***2/x64/lib/python3.8/site-packages/requests/api.py", line 6***, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.***2/x64/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/opt/hostedtoolcache/Python/3.8.***2/x64/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/opt/hostedtoolcache/Python/3.8.***2/x64/lib/python3.8/site-packages/requests/models.py", line 3***6, in prepare
    self.prepare_url(url, params)
  File "/opt/hostedtoolcache/Python/3.8.***2/x64/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '***': No schema supplied. Perhaps you meant http://***?
Error: Process completed with exit code ***.
```

**Comment by roscha444** [comment]
@Marlon154 i removed the url from the secrets to check the cronjob execution a while. I added the url again, the last days the cronjob execution looks well.
